name = "StructuralAnalysis"
uuid = "683fc324-edd8-4b59-b916-753df32c43af"
authors = ["Julius Rey Baniqued <jdbaniqued1@up.edu.ph> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
